apiVersion: apps/v1
kind: Deployment
metadta:
  name: app1
  labels:
    purpose: ingerss-demo
    project: roboshop
    app: app1
spec:
  replicas: 2
  selector:
    matchlabels:
      purpose: ingress-demo
      project: roboshop
      app: app1
  template:
    metadata:
      labels:
        purpose: ingerss-demo
        project: roboshop
        app: app1
    spec:
      containers:
      - name: app1
        image: shivv16/app1:v1

----

apiVersion: v1
kind: Service
metadata:
  name: app1
spec:
  selector:
    purpose: ingress-demo
    project: roboshop
    app: app1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
-----

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app1
  annotations:
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:339712954024:certificate/7fb2af23-4e93-4ac8-b7f6-2fc1be796913
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/tags: Environment=dev,Project=roboshop
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: roboshop
spec:
  ingressClassName: alb
  rules:
  - host: "app1.shivv-aws.fun"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: app1
            port:
              number: 80